use oxide_torch::{Error, Result};
use serde::Deserialize;
use std::collections::HashMap;

/// Generation parameters matching `google/gemma-4-E2B-it` defaults.
#[derive(Clone, Debug)]
pub struct GenerationConfig {
    pub max_new_tokens: usize,
    pub temperature: f32,
    pub top_k: usize,
    pub top_p: f32,
    pub eos_token_ids: Vec<u32>,
    /// Penalizes tokens already generated by this call. `1.0` disables it.
    pub repetition_penalty: f32,
    /// Additional token sequences which terminate generation when matched.
    pub stop_token_sequences: Vec<Vec<u32>>,
    pub seed: u64,
}

impl Default for GenerationConfig {
    fn default() -> Self {
        Self {
            max_new_tokens: 128,
            temperature: 1.0,
            top_k: 64,
            top_p: 0.95,
            eos_token_ids: vec![1, 50, 106],
            repetition_penalty: 1.1,
            stop_token_sequences: Vec::new(),
            seed: 0x4d59_5df4_d0f3_3173,
        }
    }
}

/// Per-layer autoregressive key/value state in `[sequence, kv_head, head_dim]` order.
fn default_vocab_size() -> usize {
    262_144
}
fn default_hidden_size() -> usize {
    2_304
}
fn default_intermediate_size() -> usize {
    9_216
}
fn default_layers() -> usize {
    30
}
fn default_heads() -> usize {
    8
}
fn default_kv_heads() -> usize {
    4
}
fn default_head_dim() -> usize {
    256
}
fn default_global_head_dim() -> usize {
    512
}
fn default_max_positions() -> usize {
    131_072
}
fn default_sliding_window() -> usize {
    512
}
fn default_eps() -> f32 {
    1e-6
}
fn default_ple_vocab() -> usize {
    262_144
}
fn default_ple_dim() -> usize {
    256
}
fn default_true() -> bool {
    true
}

fn default_rope_theta() -> f32 {
    10_000.0
}

fn default_rope_factor() -> f32 {
    1.0
}

/// Per-layer-type rotary embedding parameters from Hugging Face config.
#[derive(Clone, Debug, Deserialize)]
pub struct Gemma4RopeParameters {
    #[serde(default = "default_rope_theta")]
    pub rope_theta: f32,
    #[serde(default)]
    pub rope_type: String,
    #[serde(default = "default_rope_factor")]
    pub partial_rotary_factor: f32,
    #[serde(default = "default_rope_factor")]
    pub factor: f32,
}

/// Hugging Face compatible `Gemma4TextConfig` subset used by the Rust model.
#[derive(Clone, Debug, Deserialize)]
#[allow(clippy::struct_excessive_bools)]
pub struct Gemma4TextConfig {
    #[serde(default = "default_vocab_size")]
    pub vocab_size: usize,
    #[serde(default = "default_hidden_size")]
    pub hidden_size: usize,
    #[serde(default = "default_intermediate_size")]
    pub intermediate_size: usize,
    #[serde(default = "default_layers")]
    pub num_hidden_layers: usize,
    #[serde(default = "default_heads")]
    pub num_attention_heads: usize,
    #[serde(default = "default_kv_heads")]
    pub num_key_value_heads: usize,
    #[serde(default)]
    pub num_global_key_value_heads: Option<usize>,
    #[serde(default = "default_head_dim")]
    pub head_dim: usize,
    #[serde(default = "default_global_head_dim")]
    pub global_head_dim: usize,
    #[serde(default = "default_max_positions")]
    pub max_position_embeddings: usize,
    #[serde(default = "default_sliding_window")]
    pub sliding_window: usize,
    #[serde(default = "default_eps")]
    pub rms_norm_eps: f32,
    #[serde(default)]
    pub layer_types: Option<Vec<String>>,
    #[serde(default = "default_ple_vocab")]
    pub vocab_size_per_layer_input: usize,
    #[serde(default = "default_ple_dim")]
    pub hidden_size_per_layer_input: usize,
    #[serde(default)]
    pub attention_k_eq_v: bool,
    #[serde(default)]
    pub num_kv_shared_layers: usize,
    #[serde(default)]
    pub enable_moe_block: bool,
    #[serde(default)]
    pub use_double_wide_mlp: bool,
    #[serde(default)]
    pub final_logit_softcapping: Option<f32>,
    #[serde(default)]
    pub rope_parameters: Option<HashMap<String, Gemma4RopeParameters>>,
    #[serde(default = "default_true")]
    pub tie_word_embeddings: bool,
}

impl Gemma4TextConfig {
    pub(super) fn finish(mut self) -> Result<Self> {
        if self.num_attention_heads == 0
            || self.num_key_value_heads == 0
            || self.num_attention_heads % self.num_key_value_heads != 0
            || self.hidden_size == 0
            || self.num_hidden_layers == 0
        {
            return Err(Error::InvalidShape(
                "invalid Gemma 4 attention configuration".into(),
            ));
        }
        if self.layer_types.is_none() {
            self.layer_types = Some(
                (0..self.num_hidden_layers)
                    .map(|index| {
                        if (index + 1) % 6 == 0 || index + 1 == self.num_hidden_layers {
                            "full_attention".to_owned()
                        } else {
                            "sliding_attention".to_owned()
                        }
                    })
                    .collect(),
            );
        }
        if self
            .layer_types
            .as_ref()
            .is_some_and(|types| types.len() != self.num_hidden_layers)
        {
            return Err(Error::InvalidShape(
                "Gemma 4 layer_types length does not match num_hidden_layers".into(),
            ));
        }
        if self.rope_parameters.is_none() {
            self.rope_parameters = Some(HashMap::from([
                (
                    "sliding_attention".to_owned(),
                    Gemma4RopeParameters {
                        rope_theta: 10_000.0,
                        rope_type: "default".to_owned(),
                        partial_rotary_factor: 1.0,
                        factor: 1.0,
                    },
                ),
                (
                    "full_attention".to_owned(),
                    Gemma4RopeParameters {
                        rope_theta: 1_000_000.0,
                        rope_type: "proportional".to_owned(),
                        partial_rotary_factor: 0.25,
                        factor: 1.0,
                    },
                ),
            ]));
        }
        Ok(self)
    }
}
